Repository acm-ucr/discord, pull requests merged in 2023-07, with the labels that each got.

#30 Added welcome dm + slash commands are now dm only
  .github/workflows/main.yaml
  .gitignore
  .pylintrc
  bot/firebase_db.py
  bot/main.py
  bot/sendgrid_email.py
  build_main.sh
Labels: Verification

#35 secrets added
  bot/main.py
Labels: Ready for Review, Secrets

#37 Fixed sendgrid pylint errors
  bot/sendgrid_email.py
Labels: Repository

#38 Tech13 08/fire base pylint fix
  bot/firebase_db.py
Labels: Repository

#36 pylint errors fixed
  .github/workflows/main.yaml
  bot/main.py
  bot/server.py
Labels: Repository
